'use client'

import React, { useState } from 'react'
import { AppModal, AppModalHeader, AppModalBody, AppModalFooter } from '@/components/common/AppModal'
import { GeneratedDocument } from '@/lib/types/rental-return'
import { Printer, FileText, CheckCircle2, ShieldCheck } from 'lucide-react'

interface AutoGeneratedDocsModalProps {
  documents: GeneratedDocument[]
  billNo: string
  customerName: string
  onClose: () => void
}

export function AutoGeneratedDocsModal({
  documents,
  billNo,
  customerName,
  onClose,
}: AutoGeneratedDocsModalProps) {
  const [selectedDoc, setSelectedDoc] = useState<GeneratedDocument | null>(documents[0] || null)

  const handlePrint = () => {
    if (!selectedDoc) return
    window.print()
  }

  return (
    <AppModal isOpen={true} onClose={onClose} size="2xl">
      {/* Header */}
      <AppModalHeader
        onClose={onClose}
        icon={<CheckCircle2 className="w-6 h-6 text-emerald-600 dark:text-emerald-400" />}
      >
        <div>
          <h3 className="text-base font-bold text-slate-900 dark:text-slate-100">
            เอกสารอัตโนมัติประจำบิลคืนสินค้า
          </h3>
          <p className="text-xs text-slate-500 dark:text-slate-400">
            บิลเลขที่: <span className="font-mono font-bold text-emerald-700 dark:text-emerald-300">{billNo}</span> | ลูกค้า: {customerName}
          </p>
        </div>
      </AppModalHeader>

      {/* Body */}
      <AppModalBody className="p-0 flex flex-col md:flex-row min-h-0 flex-1 overflow-hidden">
        {/* Left sidebar: Document list */}
        <div className="w-full md:w-1/3 border-b md:border-b-0 md:border-r border-slate-200 dark:border-slate-800 p-4 space-y-2 overflow-y-auto bg-slate-50 dark:bg-slate-900/50">
          <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">
            รายการเอกสารที่สร้าง ({documents.length})
          </h4>
          {documents.map((doc) => {
            const isSelected = selectedDoc?.id === doc.id
            return (
              <button
                key={doc.id}
                onClick={() => setSelectedDoc(doc)}
                className={`w-full text-left p-3 rounded-2xl border transition-all text-xs flex flex-col gap-1 cursor-pointer ${
                  isSelected
                    ? 'border-emerald-600 bg-emerald-50 dark:bg-emerald-950/40 text-emerald-900 dark:text-emerald-200 shadow-sm font-semibold'
                    : 'border-slate-200 dark:border-slate-800 hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300'
                }`}
              >
                <div className="flex items-center justify-between font-bold">
                  <span className="truncate flex items-center gap-1.5">
                    <FileText className="w-4 h-4 text-emerald-600 shrink-0" />
                    {doc.title}
                  </span>
                </div>
                <div className="flex justify-between text-[11px] text-slate-500 font-mono">
                  <span>{doc.docNo}</span>
                  {doc.amount !== undefined && doc.amount > 0 && (
                    <span className="font-bold text-emerald-600">
                      ฿{doc.amount.toLocaleString()}
                    </span>
                  )}
                </div>
              </button>
            )
          })}
        </div>

        {/* Right content: Document Preview */}
        <div className="flex-1 p-6 overflow-y-auto bg-white dark:bg-slate-950 flex flex-col justify-between">
          {selectedDoc ? (
            <div className="space-y-6">
              {/* Paper Mockup */}
              <div className="border-2 border-dashed border-slate-200 dark:border-slate-800 p-6 rounded-2xl bg-slate-50/50 dark:bg-slate-900/50 space-y-4">
                <div className="flex justify-between items-start border-b border-slate-200 dark:border-slate-800 pb-4">
                  <div>
                    <span className="px-2.5 py-1 rounded-full bg-emerald-100 dark:bg-emerald-950 text-emerald-800 dark:text-emerald-200 font-extrabold text-[10px] tracking-wider uppercase">
                      {selectedDoc.docType}
                    </span>
                    <h2 className="text-xl font-black text-slate-900 dark:text-slate-100 mt-2">
                      {selectedDoc.title}
                    </h2>
                    <p className="text-xs text-slate-500">เลขที่เอกสาร: {selectedDoc.docNo}</p>
                  </div>
                  <div className="text-right text-xs text-slate-500">
                    <p>ออกโดย: ระบบ POS</p>
                    <p>วันที่ออก: {selectedDoc.issuedDate}</p>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4 text-xs">
                  <div>
                    <span className="text-slate-500 block">อ้างอิงบิลเช่าเดิม:</span>
                    <span className="font-bold text-blue-600">{selectedDoc.billNo}</span>
                  </div>
                  <div>
                    <span className="text-slate-500 block">ชื่อลูกค้า / บริษัท:</span>
                    <span className="font-bold text-slate-900 dark:text-slate-100">{selectedDoc.customerName}</span>
                  </div>
                </div>

                <div className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-800 space-y-2 text-xs">
                  <span className="font-bold text-slate-700 dark:text-slate-300">รายละเอียดเอกสาร:</span>
                  <p className="text-slate-600 dark:text-slate-400">{selectedDoc.description}</p>
                </div>

                {selectedDoc.amount !== undefined && (
                  <div className="flex justify-between items-center bg-emerald-50 dark:bg-emerald-950/40 p-4 rounded-xl border border-emerald-200 dark:border-emerald-900 text-xs font-bold">
                    <span className="text-emerald-900 dark:text-emerald-300">มูลค่ารวมตามเอกสารนี้:</span>
                    <span className="text-2xl font-black text-emerald-600 dark:text-emerald-400">
                      ฿{selectedDoc.amount.toLocaleString('th-TH', { minimumFractionDigits: 2 })}
                    </span>
                  </div>
                )}
              </div>
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center h-full text-slate-400 py-12">
              <FileText className="w-12 h-12 mb-2" />
              <p>เลือกเอกสารที่ต้องการดูตัวอย่าง</p>
            </div>
          )}
        </div>
      </AppModalBody>

      {/* Footer */}
      <AppModalFooter>
        <div className="flex-1 flex justify-between items-center w-full">
          <span className="text-xs text-slate-400 flex items-center gap-1">
            <ShieldCheck className="w-4 h-4 text-emerald-500" />
            เอกสารสร้างและลงนามโดยระบบอัตโนมัติ
          </span>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-extrabold text-xs shadow-md flex items-center gap-1.5 cursor-pointer"
            >
              <Printer className="w-4 h-4" />
              <span>พิมพ์เอกสารนี้</span>
            </button>
            <button
              onClick={onClose}
              className="px-5 py-2 rounded-xl bg-slate-200 dark:bg-slate-800 hover:bg-slate-300 text-slate-800 dark:text-slate-200 font-bold text-xs cursor-pointer"
            >
              ปิดหน้าต่าง
            </button>
          </div>
        </div>
      </AppModalFooter>
    </AppModal>
  )
}

