-- 1. CUSTOMER SCHEMA ALIGNMENT
ALTER TABLE public.customers
  ADD COLUMN IF NOT EXISTS customer_type TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN IF NOT EXISTS phone2 TEXT,
  ADD COLUMN IF NOT EXISTS line_id TEXT,
  ADD COLUMN IF NOT EXISTS house_no TEXT,
  ADD COLUMN IF NOT EXISTS moo TEXT,
  ADD COLUMN IF NOT EXISTS soi TEXT,
  ADD COLUMN IF NOT EXISTS road TEXT,
  ADD COLUMN IF NOT EXISTS sub_district TEXT,
  ADD COLUMN IF NOT EXISTS district TEXT,
  ADD COLUMN IF NOT EXISTS province TEXT,
  ADD COLUMN IF NOT EXISTS postal_code TEXT,
  ADD COLUMN IF NOT EXISTS id_card_image_url TEXT,
  ADD COLUMN IF NOT EXISTS is_suspended BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS note TEXT;
